### PR TITLE
add coloredlogs dependency

### PR DESCRIPTION
**Pull request by pvanheus**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
Sorry, I am currently traveling and cannot review carefully.
What is very important here is that all the versions constraints in cwltools setup.py are exactly mirrored here in the meta.yaml. Otherwise there will be runtime errors.

Can you double check that everything’s fine and I will merge.

**Comment by mr-c** [comment]
Thank you all. Are the tests run as part of the build? We make a lot of effort to include the tests in the installed package and to make them portable.

**Comment by pvanheus** [comment]
> Sorry, I am currently traveling and cannot review carefully.
> What is very important here is that all the versions constraints in cwltools setup.py are exactly mirrored here in the meta.yaml. Otherwise there will be runtime errors.
> 
> Can you double check that everything’s fine and I will merge.

Thanks for the tip. I noticed that the latest cwltool relies on an updated schema-salad, so I have done a PR for that: https://github.com/conda-forge/schema-salad-feedstock/pull/18 - that needs to be merged before I can update this PR. To ease the load I have added myself as a maintainer on this and the schema-salad feedstocks.

**Comment by pvanheus** [comment]
> Thank you all. Are the tests run as part of the build? We make a lot of effort to include the tests in the installed package and to make them portable.

The only tests that are run by this recipe are the moment are 2 import tests - `cwltool` and `cwltool.tests` and one command test `cwltool --help`. They are intended to test whether the conda recipe works, I think the tests of cwltool itself should be handled by cwltool CI.

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
@pvanheus, I updated cwltool this morning in this PR and added you as a maintainer! https://github.com/conda-forge/cwltool-feedstock/pull/19.

**Pull request closed without merging**
